# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'audioUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(448, 149)
        self.audiofilebutton = QtWidgets.QPushButton(Form)
        self.audiofilebutton.setGeometry(QtCore.QRect(230, 10, 81, 26))
        self.audiofilebutton.setStyleSheet("background-color: rgb(25, 144, 26);")
        self.audiofilebutton.setCheckable(False)
        self.audiofilebutton.setObjectName("audiofilebutton")
        self.audiopath = QtWidgets.QTextEdit(Form)
        self.audiopath.setGeometry(QtCore.QRect(20, 10, 191, 41))
        self.audiopath.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.audiopath.setObjectName("audiopath")
        self.addbutton = QtWidgets.QPushButton(Form)
        self.addbutton.setGeometry(QtCore.QRect(400, 20, 31, 26))
        self.addbutton.setStyleSheet("background-color: rgb(53, 61, 255);")
        self.addbutton.setObjectName("addbutton")
        self.subtractbutton = QtWidgets.QPushButton(Form)
        self.subtractbutton.setGeometry(QtCore.QRect(320, 20, 31, 26))
        self.subtractbutton.setStyleSheet("background-color: rgb(53, 61, 255);")
        self.subtractbutton.setObjectName("subtractbutton")
        self.value = QtWidgets.QLineEdit(Form)
        self.value.setGeometry(QtCore.QRect(360, 20, 31, 31))
        self.value.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.value.setAlignment(QtCore.Qt.AlignCenter)
        self.value.setObjectName("value")
        self.savebackbutton = QtWidgets.QPushButton(Form)
        self.savebackbutton.setGeometry(QtCore.QRect(220, 100, 41, 31))
        self.savebackbutton.setStyleSheet("background-color: rgb(210, 51, 255);")
        self.savebackbutton.setObjectName("savebackbutton")
        self.savefilebutton = QtWidgets.QPushButton(Form)
        self.savefilebutton.setGeometry(QtCore.QRect(280, 100, 61, 31))
        self.savefilebutton.setStyleSheet("\n"
"background-color: rgb(28, 179, 178);")
        self.savefilebutton.setObjectName("savefilebutton")
        self.playbutton1 = QtWidgets.QPushButton(Form)
        self.playbutton1.setGeometry(QtCore.QRect(20, 60, 80, 30))
        self.playbutton1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.playbutton1.setObjectName("playbutton1")
        self.playbutton2 = QtWidgets.QPushButton(Form)
        self.playbutton2.setGeometry(QtCore.QRect(120, 60, 80, 30))
        self.playbutton2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.playbutton2.setObjectName("playbutton2")
        self.play1value = QtWidgets.QLineEdit(Form)
        self.play1value.setGeometry(QtCore.QRect(20, 110, 80, 20))
        self.play1value.setAlignment(QtCore.Qt.AlignCenter)
        self.play1value.setObjectName("play1value")
        self.play2value = QtWidgets.QLineEdit(Form)
        self.play2value.setGeometry(QtCore.QRect(120, 110, 80, 20))
        self.play2value.setAlignment(QtCore.Qt.AlignCenter)
        self.play2value.setObjectName("play2value")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "音量修改"))
        self.audiofilebutton.setText(_translate("Form", "開檔(單一)"))
        self.audiopath.setPlaceholderText(_translate("Form", "輸入完整檔案路徑"))
        self.addbutton.setText(_translate("Form", "＋"))
        self.subtractbutton.setText(_translate("Form", "-"))
        self.savebackbutton.setText(_translate("Form", "回存"))
        self.savefilebutton.setText(_translate("Form", "另存新檔"))
        self.playbutton1.setText(_translate("Form", "原始音檔播放"))
        self.playbutton2.setText(_translate("Form", "新音檔播放"))
        self.play1value.setPlaceholderText(_translate("Form", "輸入秒數"))
        self.play2value.setPlaceholderText(_translate("Form", "輸入秒數"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
